---
title: "p8106_hw6"
author: "Nathalie Fadel"
date: "4/29/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Hierarchical Clustering

###Part A
```{r}
library(ISLR)
library(tidyverse)
library(factoextra)

data("USArrests")
summary(USArrests)

usa.dist <- dist(USArrests)
usa.hclust <- hclust(usa.dist, method = "complete")

fviz_dend(usa.hclust, k = 4,        
          cex = 0.3, 
          palette = "jco", 
          color_labels_by_k = TRUE,
          rect = TRUE, rect_fill = TRUE, rect_border = "jco",
          labels_track_height = 20)
```

###Part B
```{r}
fviz_dend(usa.hclust, k = 3,        
          cex = 0.3, 
          palette = "jco", 
          color_labels_by_k = TRUE,
          rect = TRUE, rect_fill = TRUE, rect_border = "jco",
          labels_track_height = 20)

ind4.complete <- cutree(usa.hclust, 3)

#Cluster 1 states
USArrests[ind4.complete == 1,]

#Cluster 2 states
USArrests[ind4.complete == 2,]

#Cluster 3 states
USArrests[ind4.complete == 3,]
```

###Part C
```{r}
scaling <- function(x)
  (x - mean(x, na.rm = TRUE)) / sd(x, na.rm = TRUE)

clust.scaled <- USArrests %>%
    map_df(scaling) %>%
    dist(method = 'euclidean') %>%
    hclust(method = 'complete')

clust.scaled$labels <- row.names(USArrests)[clust.scaled$order]

fviz_dend(clust.scaled, k = 4,        
          cex = 0.3, 
          palette = "jco", 
          color_labels_by_k = TRUE,
          rect = TRUE, rect_fill = TRUE, rect_border = "jco",
          labels_track_height = 2.5)

```

###Part D

We should be scaling the variables prior to computing the Euclidean distance. Otherwise, variables with larger values will dominate over smaller ones. 

##PCA

```{r}
library(jpeg)

img <- readJPEG('cat.jpg')

dim(img)

r <- img[,,1]
g <- img[,,2]
b <- img[,,3]

img.r.pca <- prcomp(r, center = FALSE)
img.g.pca <- prcomp(g, center = FALSE)
img.b.pca <- prcomp(b, center = FALSE)

rgb.pca <- list(img.r.pca, img.g.pca, img.b.pca)

# Approximate X with XV_kV_k^T
compress <- function(pr, k)
{
  compressed.img <- pr$x[,1:k] %*% t(pr$rotation[,1:k])
  compressed.img
}

# Using first 20 PCs
pca20 <- sapply(rgb.pca, compress, k = 20, simplify = "array")

writeJPEG(pca20, "pca20.jpeg")

# Try to increase the number of PCs!

pca50 <- sapply(rgb.pca, compress, k = 50, simplify = "array")

writeJPEG(pca50, "pca50.jpeg")
```


```{r}
#Using another photo
newimg <- readJPEG('puppy.jpg')

dim(newimg)

r <- newimg[,,1]
g <- newimg[,,2]
b <- newimg[,,3]

img.r.pca <- prcomp(r, center = FALSE)
img.g.pca <- prcomp(g, center = FALSE)
img.b.pca <- prcomp(b, center = FALSE)

rgb.pca <- list(img.r.pca, img.g.pca, img.b.pca)

# Approximate X with XV_kV_k^T
compress <- function(pr, k)
{
  compressed.img <- pr$x[,1:k] %*% t(pr$rotation[,1:k])
  compressed.img
}

#with 50 PCs
pup.pca50 <- sapply(rgb.pca, compress, k = 50, simplify = "array")

writeJPEG(pup.pca50, "pup50.jpeg")

#100 PCs
pup.pca100 <- sapply(rgb.pca, compress, k = 100, simplify = "array")

writeJPEG(pup.pca100, "pup100.jpeg")

#200 PCs
pup.pca200 <- sapply(rgb.pca, compress, k = 200, simplify = "array")

writeJPEG(pup.pca200, "pup200.jpeg")

```
